### ISSUE TITLE
Incorrect highlight function return type

### ISSUE THREAD

**Issue by saharNooby** [guilhermelimak/react-codejar#20]
In `index.tsx`, line 17:
```
  highlight: (e: HTMLElement) => {};
```

Here signature should be `(e: HTMLElement) => void;`, that is instead of `{}` there must be `void`.

Because of this, library user needs to add useless `return {};` to the end of highlighter function.

Signature change will not break existing typed code because returned value (in this case empty object) will be ignored when the function is cast to void returning type.

Note that in https://github.com/antonmedv/codejar/blob/master/codejar.ts (line 27) there is correct `void` return type in highlighter function.

Sorry for not creating pull request, I'm not familiar with JS/TS module development.

**Comment by guilhermelimak** [comment]
Thanks for the heads up, just published version 1.1.2 that should fix that.
